// Mocks generated by Mockito 5.4.6 from annotations
// in driver/test/features/documents/repositories/driver_document_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:built_collection/built_collection.dart' as _i22;
import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/src/api.dart' as _i10;
import 'package:sakai_api_client/src/api/admin_api.dart' as _i4;
import 'package:sakai_api_client/src/api/auth_api.dart' as _i5;
import 'package:sakai_api_client/src/api/driver_api.dart' as _i6;
import 'package:sakai_api_client/src/api/rides_api.dart' as _i7;
import 'package:sakai_api_client/src/api/system_api.dart' as _i8;
import 'package:sakai_api_client/src/api/users_api.dart' as _i9;
import 'package:sakai_api_client/src/model/admin_list_driver_rides200_response.dart'
    as _i12;
import 'package:sakai_api_client/src/model/date.dart' as _i15;
import 'package:sakai_api_client/src/model/driver_document_response.dart'
    as _i13;
import 'package:sakai_api_client/src/model/driver_documents_list_response.dart'
    as _i18;
import 'package:sakai_api_client/src/model/driver_get_earnings200_response.dart'
    as _i14;
import 'package:sakai_api_client/src/model/driver_status_request.dart' as _i19;
import 'package:sakai_api_client/src/model/driver_status_response.dart' as _i17;
import 'package:sakai_api_client/src/model/get_nearby_drivers200_response.dart'
    as _i21;
import 'package:sakai_api_client/src/model/location_update_request.dart'
    as _i20;
import 'package:sakai_api_client/src/model/nearby_driver.dart' as _i23;
import 'package:sakai_api_client/src/model/ride_response.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminApi_2 extends _i1.SmartFake implements _i4.AdminApi {
  _FakeAdminApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthApi_3 extends _i1.SmartFake implements _i5.AuthApi {
  _FakeAuthApi_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriverApi_4 extends _i1.SmartFake implements _i6.DriverApi {
  _FakeDriverApi_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRidesApi_5 extends _i1.SmartFake implements _i7.RidesApi {
  _FakeRidesApi_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemApi_6 extends _i1.SmartFake implements _i8.SystemApi {
  _FakeSystemApi_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersApi_7 extends _i1.SmartFake implements _i9.UsersApi {
  _FakeUsersApi_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_8<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SakaiApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSakaiApiClient extends _i1.Mock implements _i10.SakaiApiClient {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
            returnValueForMissingStub: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.AdminApi getAdminApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminApi, []),
            returnValue: _FakeAdminApi_2(
              this,
              Invocation.method(#getAdminApi, []),
            ),
            returnValueForMissingStub: _FakeAdminApi_2(
              this,
              Invocation.method(#getAdminApi, []),
            ),
          )
          as _i4.AdminApi);

  @override
  _i5.AuthApi getAuthApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthApi, []),
            returnValue: _FakeAuthApi_3(
              this,
              Invocation.method(#getAuthApi, []),
            ),
            returnValueForMissingStub: _FakeAuthApi_3(
              this,
              Invocation.method(#getAuthApi, []),
            ),
          )
          as _i5.AuthApi);

  @override
  _i6.DriverApi getDriverApi() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverApi, []),
            returnValue: _FakeDriverApi_4(
              this,
              Invocation.method(#getDriverApi, []),
            ),
            returnValueForMissingStub: _FakeDriverApi_4(
              this,
              Invocation.method(#getDriverApi, []),
            ),
          )
          as _i6.DriverApi);

  @override
  _i7.RidesApi getRidesApi() =>
      (super.noSuchMethod(
            Invocation.method(#getRidesApi, []),
            returnValue: _FakeRidesApi_5(
              this,
              Invocation.method(#getRidesApi, []),
            ),
            returnValueForMissingStub: _FakeRidesApi_5(
              this,
              Invocation.method(#getRidesApi, []),
            ),
          )
          as _i7.RidesApi);

  @override
  _i8.SystemApi getSystemApi() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemApi, []),
            returnValue: _FakeSystemApi_6(
              this,
              Invocation.method(#getSystemApi, []),
            ),
            returnValueForMissingStub: _FakeSystemApi_6(
              this,
              Invocation.method(#getSystemApi, []),
            ),
          )
          as _i8.SystemApi);

  @override
  _i9.UsersApi getUsersApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUsersApi, []),
            returnValue: _FakeUsersApi_7(
              this,
              Invocation.method(#getUsersApi, []),
            ),
            returnValueForMissingStub: _FakeUsersApi_7(
              this,
              Invocation.method(#getUsersApi, []),
            ),
          )
          as _i9.UsersApi);
}

/// A class which mocks [DriverApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverApi extends _i1.Mock implements _i6.DriverApi {
  @override
  _i11.Future<_i2.Response<_i12.AdminListDriverRides200Response>>
  adminListDriverRides({
    int? page = 1,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adminListDriverRides, [], {
              #page: page,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<_i12.AdminListDriverRides200Response>
                >.value(
                  _FakeResponse_8<_i12.AdminListDriverRides200Response>(
                    this,
                    Invocation.method(#adminListDriverRides, [], {
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Response<_i12.AdminListDriverRides200Response>
                >.value(
                  _FakeResponse_8<_i12.AdminListDriverRides200Response>(
                    this,
                    Invocation.method(#adminListDriverRides, [], {
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i12.AdminListDriverRides200Response>>);

  @override
  _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>
  driverGetDocumentStatus({
    required String? documentId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetDocumentStatus, [], {
              #documentId: documentId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>.value(
                  _FakeResponse_8<_i13.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverGetDocumentStatus, [], {
                      #documentId: documentId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>.value(
                  _FakeResponse_8<_i13.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverGetDocumentStatus, [], {
                      #documentId: documentId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>);

  @override
  _i11.Future<_i2.Response<_i14.DriverGetEarnings200Response>>
  driverGetEarnings({
    _i15.Date? from,
    _i15.Date? to,
    int? page = 1,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetEarnings, [], {
              #from: from,
              #to: to,
              #page: page,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<_i14.DriverGetEarnings200Response>
                >.value(
                  _FakeResponse_8<_i14.DriverGetEarnings200Response>(
                    this,
                    Invocation.method(#driverGetEarnings, [], {
                      #from: from,
                      #to: to,
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Response<_i14.DriverGetEarnings200Response>
                >.value(
                  _FakeResponse_8<_i14.DriverGetEarnings200Response>(
                    this,
                    Invocation.method(#driverGetEarnings, [], {
                      #from: from,
                      #to: to,
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i14.DriverGetEarnings200Response>>);

  @override
  _i11.Future<_i2.Response<_i16.RideResponse>> driverGetIncomingRide({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetIncomingRide, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i16.RideResponse>>.value(
              _FakeResponse_8<_i16.RideResponse>(
                this,
                Invocation.method(#driverGetIncomingRide, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i11.Future<_i2.Response<_i16.RideResponse>>.value(
                  _FakeResponse_8<_i16.RideResponse>(
                    this,
                    Invocation.method(#driverGetIncomingRide, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i16.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.DriverStatusResponse>> driverGetStatus({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetStatus, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i17.DriverStatusResponse>>.value(
                  _FakeResponse_8<_i17.DriverStatusResponse>(
                    this,
                    Invocation.method(#driverGetStatus, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Response<_i17.DriverStatusResponse>>.value(
                  _FakeResponse_8<_i17.DriverStatusResponse>(
                    this,
                    Invocation.method(#driverGetStatus, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i17.DriverStatusResponse>>);

  @override
  _i11.Future<_i2.Response<_i18.DriverDocumentsListResponse>>
  driverListDocuments({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverListDocuments, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<_i18.DriverDocumentsListResponse>
                >.value(
                  _FakeResponse_8<_i18.DriverDocumentsListResponse>(
                    this,
                    Invocation.method(#driverListDocuments, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Response<_i18.DriverDocumentsListResponse>
                >.value(
                  _FakeResponse_8<_i18.DriverDocumentsListResponse>(
                    this,
                    Invocation.method(#driverListDocuments, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i18.DriverDocumentsListResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.DriverStatusResponse>> driverSetStatus({
    required _i19.DriverStatusRequest? driverStatusRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverSetStatus, [], {
              #driverStatusRequest: driverStatusRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i17.DriverStatusResponse>>.value(
                  _FakeResponse_8<_i17.DriverStatusResponse>(
                    this,
                    Invocation.method(#driverSetStatus, [], {
                      #driverStatusRequest: driverStatusRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Response<_i17.DriverStatusResponse>>.value(
                  _FakeResponse_8<_i17.DriverStatusResponse>(
                    this,
                    Invocation.method(#driverSetStatus, [], {
                      #driverStatusRequest: driverStatusRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i17.DriverStatusResponse>>);

  @override
  _i11.Future<_i2.Response<void>> driverUpdateLocation({
    required _i20.LocationUpdateRequest? locationUpdateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverUpdateLocation, [], {
              #locationUpdateRequest: locationUpdateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#driverUpdateLocation, [], {
                  #locationUpdateRequest: locationUpdateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#driverUpdateLocation, [], {
                  #locationUpdateRequest: locationUpdateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<void>>);

  @override
  _i11.Future<_i2.Response<_i13.DriverDocumentResponse>> driverUploadDocument({
    required String? documentType,
    required String? documentNumber,
    required _i2.MultipartFile? image,
    _i15.Date? expiryDate,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverUploadDocument, [], {
              #documentType: documentType,
              #documentNumber: documentNumber,
              #image: image,
              #expiryDate: expiryDate,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>.value(
                  _FakeResponse_8<_i13.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverUploadDocument, [], {
                      #documentType: documentType,
                      #documentNumber: documentNumber,
                      #image: image,
                      #expiryDate: expiryDate,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>.value(
                  _FakeResponse_8<_i13.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverUploadDocument, [], {
                      #documentType: documentType,
                      #documentNumber: documentNumber,
                      #image: image,
                      #expiryDate: expiryDate,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i13.DriverDocumentResponse>>);

  @override
  _i11.Future<_i2.Response<_i21.GetNearbyDrivers200Response>> getNearbyDrivers({
    required double? lat,
    required double? lng,
    required String? rideType,
    double? radiusM = 5000.0,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyDrivers, [], {
              #lat: lat,
              #lng: lng,
              #rideType: rideType,
              #radiusM: radiusM,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<_i21.GetNearbyDrivers200Response>
                >.value(
                  _FakeResponse_8<_i21.GetNearbyDrivers200Response>(
                    this,
                    Invocation.method(#getNearbyDrivers, [], {
                      #lat: lat,
                      #lng: lng,
                      #rideType: rideType,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Response<_i21.GetNearbyDrivers200Response>
                >.value(
                  _FakeResponse_8<_i21.GetNearbyDrivers200Response>(
                    this,
                    Invocation.method(#getNearbyDrivers, [], {
                      #lat: lat,
                      #lng: lng,
                      #rideType: rideType,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i21.GetNearbyDrivers200Response>>);

  @override
  _i11.Future<
    _i2.Response<_i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>>
  >
  getNearbyDriversAllTypes({
    required double? lat,
    required double? lng,
    double? radiusM = 5000.0,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyDriversAllTypes, [], {
              #lat: lat,
              #lng: lng,
              #radiusM: radiusM,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<
                    _i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>
                  >
                >.value(
                  _FakeResponse_8<
                    _i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>
                  >(
                    this,
                    Invocation.method(#getNearbyDriversAllTypes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i11.Future<
                  _i2.Response<
                    _i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>
                  >
                >.value(
                  _FakeResponse_8<
                    _i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>
                  >(
                    this,
                    Invocation.method(#getNearbyDriversAllTypes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<
            _i2.Response<
              _i22.BuiltMap<String, _i22.BuiltList<_i23.NearbyDriver>>
            >
          >);
}
