// Mocks generated by Mockito 5.4.6 from annotations
// in driver/test/features/documents/view_models/document_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:driver/features/documents/repositories/driver_document_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/sakai_api_client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDriverDocumentResponse_0 extends _i1.SmartFake
    implements _i2.DriverDocumentResponse {
  _FakeDriverDocumentResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DriverDocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverDocumentRepository extends _i1.Mock
    implements _i3.DriverDocumentRepository {
  MockDriverDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.DriverDocumentResponse>> listDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#listDocuments, []),
            returnValue: _i4.Future<List<_i2.DriverDocumentResponse>>.value(
              <_i2.DriverDocumentResponse>[],
            ),
          )
          as _i4.Future<List<_i2.DriverDocumentResponse>>);

  @override
  _i4.Future<_i2.DriverDocumentResponse> uploadDocument({
    required String? documentType,
    required String? documentNumber,
    required String? imagePath,
    DateTime? expiryDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [], {
              #documentType: documentType,
              #documentNumber: documentNumber,
              #imagePath: imagePath,
              #expiryDate: expiryDate,
            }),
            returnValue: _i4.Future<_i2.DriverDocumentResponse>.value(
              _FakeDriverDocumentResponse_0(
                this,
                Invocation.method(#uploadDocument, [], {
                  #documentType: documentType,
                  #documentNumber: documentNumber,
                  #imagePath: imagePath,
                  #expiryDate: expiryDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.DriverDocumentResponse>);

  @override
  _i4.Future<_i2.DriverDocumentResponse> getDocumentStatus(
    String? documentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDocumentStatus, [documentId]),
            returnValue: _i4.Future<_i2.DriverDocumentResponse>.value(
              _FakeDriverDocumentResponse_0(
                this,
                Invocation.method(#getDocumentStatus, [documentId]),
              ),
            ),
          )
          as _i4.Future<_i2.DriverDocumentResponse>);
}
