// Code generated by MockGen. DO NOT EDIT.
// Source: e:\Projects\SakAI\backend\internal\domain\ports.go
//
// Generated by this command:
//
//	mockgen -source=e:\Projects\SakAI\backend\internal\domain\ports.go -destination=e:\Projects\SakAI\backend\internal\domain\mocks\mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/sakai/backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// CreateWithTokens mocks base method.
func (m *MockUserRepository) CreateWithTokens(ctx context.Context, user *domain.User, refreshToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTokens", ctx, user, refreshToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTokens indicates an expected call of CreateWithTokens.
func (mr *MockUserRepositoryMockRecorder) CreateWithTokens(ctx, user, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTokens", reflect.TypeOf((*MockUserRepository)(nil).CreateWithTokens), ctx, user, refreshToken, expiresAt)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTokenRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTokenRepository)(nil).Delete), ctx, token)
}

// GetUserID mocks base method.
func (m *MockTokenRepository) GetUserID(ctx context.Context, token string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockTokenRepositoryMockRecorder) GetUserID(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockTokenRepository)(nil).GetUserID), ctx, token)
}

// Store mocks base method.
func (m *MockTokenRepository) Store(ctx context.Context, userID uuid.UUID, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTokenRepositoryMockRecorder) Store(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTokenRepository)(nil).Store), ctx, userID, token, expiresAt)
}

// MockRideRepository is a mock of RideRepository interface.
type MockRideRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRideRepositoryMockRecorder
	isgomock struct{}
}

// MockRideRepositoryMockRecorder is the mock recorder for MockRideRepository.
type MockRideRepositoryMockRecorder struct {
	mock *MockRideRepository
}

// NewMockRideRepository creates a new mock instance.
func NewMockRideRepository(ctrl *gomock.Controller) *MockRideRepository {
	mock := &MockRideRepository{ctrl: ctrl}
	mock.recorder = &MockRideRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideRepository) EXPECT() *MockRideRepositoryMockRecorder {
	return m.recorder
}

// AssignDriver mocks base method.
func (m *MockRideRepository) AssignDriver(ctx context.Context, rideID, driverID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, rideID, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockRideRepositoryMockRecorder) AssignDriver(ctx, rideID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockRideRepository)(nil).AssignDriver), ctx, rideID, driverID)
}

// CancelExpiredOffers mocks base method.
func (m *MockRideRepository) CancelExpiredOffers(ctx context.Context, timeout time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExpiredOffers", ctx, timeout)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelExpiredOffers indicates an expected call of CancelExpiredOffers.
func (mr *MockRideRepositoryMockRecorder) CancelExpiredOffers(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExpiredOffers", reflect.TypeOf((*MockRideRepository)(nil).CancelExpiredOffers), ctx, timeout)
}

// ClearDriver mocks base method.
func (m *MockRideRepository) ClearDriver(ctx context.Context, rideID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDriver", ctx, rideID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDriver indicates an expected call of ClearDriver.
func (mr *MockRideRepositoryMockRecorder) ClearDriver(ctx, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDriver", reflect.TypeOf((*MockRideRepository)(nil).ClearDriver), ctx, rideID)
}

// Create mocks base method.
func (m *MockRideRepository) Create(ctx context.Context, ride *domain.Ride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ride)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRideRepositoryMockRecorder) Create(ctx, ride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRideRepository)(nil).Create), ctx, ride)
}

// GetActiveByDriverID mocks base method.
func (m *MockRideRepository) GetActiveByDriverID(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByDriverID", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByDriverID indicates an expected call of GetActiveByDriverID.
func (mr *MockRideRepositoryMockRecorder) GetActiveByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByDriverID", reflect.TypeOf((*MockRideRepository)(nil).GetActiveByDriverID), ctx, driverID)
}

// GetActiveByPassengerID mocks base method.
func (m *MockRideRepository) GetActiveByPassengerID(ctx context.Context, passengerID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByPassengerID indicates an expected call of GetActiveByPassengerID.
func (mr *MockRideRepositoryMockRecorder) GetActiveByPassengerID(ctx, passengerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByPassengerID", reflect.TypeOf((*MockRideRepository)(nil).GetActiveByPassengerID), ctx, passengerID)
}

// GetByID mocks base method.
func (m *MockRideRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRideRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRideRepository)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockRideRepository) GetByIdempotencyKey(ctx context.Context, key string) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockRideRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockRideRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// SetCancelled mocks base method.
func (m *MockRideRepository) SetCancelled(ctx context.Context, id uuid.UUID, by domain.CancelledBy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCancelled", ctx, id, by)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCancelled indicates an expected call of SetCancelled.
func (mr *MockRideRepositoryMockRecorder) SetCancelled(ctx, id, by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelled", reflect.TypeOf((*MockRideRepository)(nil).SetCancelled), ctx, id, by)
}

// UpdateStatus mocks base method.
func (m *MockRideRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.RideStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRideRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRideRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockDriverRepository is a mock of DriverRepository interface.
type MockDriverRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriverRepositoryMockRecorder
	isgomock struct{}
}

// MockDriverRepositoryMockRecorder is the mock recorder for MockDriverRepository.
type MockDriverRepositoryMockRecorder struct {
	mock *MockDriverRepository
}

// NewMockDriverRepository creates a new mock instance.
func NewMockDriverRepository(ctrl *gomock.Controller) *MockDriverRepository {
	mock := &MockDriverRepository{ctrl: ctrl}
	mock.recorder = &MockDriverRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverRepository) EXPECT() *MockDriverRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDriverRepository) Create(ctx context.Context, driver *domain.Driver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDriverRepositoryMockRecorder) Create(ctx, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriverRepository)(nil).Create), ctx, driver)
}

// FindNearbyOnline mocks base method.
func (m *MockDriverRepository) FindNearbyOnline(ctx context.Context, origin domain.LatLng, radiusMeters float64) ([]*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyOnline", ctx, origin, radiusMeters)
	ret0, _ := ret[0].([]*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearbyOnline indicates an expected call of FindNearbyOnline.
func (mr *MockDriverRepositoryMockRecorder) FindNearbyOnline(ctx, origin, radiusMeters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyOnline", reflect.TypeOf((*MockDriverRepository)(nil).FindNearbyOnline), ctx, origin, radiusMeters)
}

// GetByUserID mocks base method.
func (m *MockDriverRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDriverRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDriverRepository)(nil).GetByUserID), ctx, userID)
}

// UpdateLocation mocks base method.
func (m *MockDriverRepository) UpdateLocation(ctx context.Context, userID uuid.UUID, loc domain.DriverLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, userID, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockDriverRepositoryMockRecorder) UpdateLocation(ctx, userID, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockDriverRepository)(nil).UpdateLocation), ctx, userID, loc)
}

// UpdateStatus mocks base method.
func (m *MockDriverRepository) UpdateStatus(ctx context.Context, userID uuid.UUID, status domain.DriverStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDriverRepositoryMockRecorder) UpdateStatus(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDriverRepository)(nil).UpdateStatus), ctx, userID, status)
}

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
	isgomock struct{}
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockAuthUseCase) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthUseCaseMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthUseCase)(nil).GetUserByID), ctx, id)
}

// Login mocks base method.
func (m *MockAuthUseCase) Login(ctx context.Context, email, password string) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthUseCaseMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthUseCase)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuthUseCase) Logout(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthUseCaseMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthUseCase)(nil).Logout), ctx, refreshToken)
}

// Refresh mocks base method.
func (m *MockAuthUseCase) Refresh(ctx context.Context, refreshToken string) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthUseCaseMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthUseCase)(nil).Refresh), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockAuthUseCase) Register(ctx context.Context, name, email, password string, role domain.UserRole, vehicle *domain.Vehicle) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, email, password, role, vehicle)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthUseCaseMockRecorder) Register(ctx, name, email, password, role, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthUseCase)(nil).Register), ctx, name, email, password, role, vehicle)
}

// MockRideUseCase is a mock of RideUseCase interface.
type MockRideUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRideUseCaseMockRecorder
	isgomock struct{}
}

// MockRideUseCaseMockRecorder is the mock recorder for MockRideUseCase.
type MockRideUseCaseMockRecorder struct {
	mock *MockRideUseCase
}

// NewMockRideUseCase creates a new mock instance.
func NewMockRideUseCase(ctrl *gomock.Controller) *MockRideUseCase {
	mock := &MockRideUseCase{ctrl: ctrl}
	mock.recorder = &MockRideUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideUseCase) EXPECT() *MockRideUseCaseMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockRideUseCase) Accept(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockRideUseCaseMockRecorder) Accept(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockRideUseCase)(nil).Accept), ctx, driverID, rideID)
}

// Arrive mocks base method.
func (m *MockRideUseCase) Arrive(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arrive", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arrive indicates an expected call of Arrive.
func (mr *MockRideUseCaseMockRecorder) Arrive(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arrive", reflect.TypeOf((*MockRideUseCase)(nil).Arrive), ctx, driverID, rideID)
}

// Cancel mocks base method.
func (m *MockRideUseCase) Cancel(ctx context.Context, userID uuid.UUID, role domain.UserRole, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, userID, role, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRideUseCaseMockRecorder) Cancel(ctx, userID, role, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRideUseCase)(nil).Cancel), ctx, userID, role, rideID)
}

// Complete mocks base method.
func (m *MockRideUseCase) Complete(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockRideUseCaseMockRecorder) Complete(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockRideUseCase)(nil).Complete), ctx, driverID, rideID)
}

// Decline mocks base method.
func (m *MockRideUseCase) Decline(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decline indicates an expected call of Decline.
func (mr *MockRideUseCaseMockRecorder) Decline(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*MockRideUseCase)(nil).Decline), ctx, driverID, rideID)
}

// GetActive mocks base method.
func (m *MockRideUseCase) GetActive(ctx context.Context, userID uuid.UUID, role domain.UserRole) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, userID, role)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockRideUseCaseMockRecorder) GetActive(ctx, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockRideUseCase)(nil).GetActive), ctx, userID, role)
}

// GetByID mocks base method.
func (m *MockRideUseCase) GetByID(ctx context.Context, userID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRideUseCaseMockRecorder) GetByID(ctx, userID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRideUseCase)(nil).GetByID), ctx, userID, rideID)
}

// RequestRide mocks base method.
func (m *MockRideUseCase) RequestRide(ctx context.Context, passengerID uuid.UUID, origin, destination domain.LatLng, originAddr, destAddr, notes, idempotencyKey string) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRide", ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRide indicates an expected call of RequestRide.
func (mr *MockRideUseCaseMockRecorder) RequestRide(ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRide", reflect.TypeOf((*MockRideUseCase)(nil).RequestRide), ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey)
}

// Start mocks base method.
func (m *MockRideUseCase) Start(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockRideUseCaseMockRecorder) Start(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRideUseCase)(nil).Start), ctx, driverID, rideID)
}

// MockDriverUseCase is a mock of DriverUseCase interface.
type MockDriverUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDriverUseCaseMockRecorder
	isgomock struct{}
}

// MockDriverUseCaseMockRecorder is the mock recorder for MockDriverUseCase.
type MockDriverUseCaseMockRecorder struct {
	mock *MockDriverUseCase
}

// NewMockDriverUseCase creates a new mock instance.
func NewMockDriverUseCase(ctrl *gomock.Controller) *MockDriverUseCase {
	mock := &MockDriverUseCase{ctrl: ctrl}
	mock.recorder = &MockDriverUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverUseCase) EXPECT() *MockDriverUseCaseMockRecorder {
	return m.recorder
}

// GetActiveRide mocks base method.
func (m *MockDriverUseCase) GetActiveRide(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRide", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRide indicates an expected call of GetActiveRide.
func (mr *MockDriverUseCaseMockRecorder) GetActiveRide(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRide", reflect.TypeOf((*MockDriverUseCase)(nil).GetActiveRide), ctx, driverID)
}

// GetIncomingRide mocks base method.
func (m *MockDriverUseCase) GetIncomingRide(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingRide", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingRide indicates an expected call of GetIncomingRide.
func (mr *MockDriverUseCaseMockRecorder) GetIncomingRide(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingRide", reflect.TypeOf((*MockDriverUseCase)(nil).GetIncomingRide), ctx, driverID)
}

// SetStatus mocks base method.
func (m *MockDriverUseCase) SetStatus(ctx context.Context, driverID uuid.UUID, status domain.DriverStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, driverID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockDriverUseCaseMockRecorder) SetStatus(ctx, driverID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockDriverUseCase)(nil).SetStatus), ctx, driverID, status)
}

// UpdateLocation mocks base method.
func (m *MockDriverUseCase) UpdateLocation(ctx context.Context, driverID uuid.UUID, loc domain.DriverLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, driverID, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockDriverUseCaseMockRecorder) UpdateLocation(ctx, driverID, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockDriverUseCase)(nil).UpdateLocation), ctx, driverID, loc)
}
