// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sakai/backend/internal/domain (interfaces: UserRepository,TokenRepository,RideRepository,DriverRepository,AdminRepository,FareRepository,AuditRepository,IncidentRepository,SystemMetricsRepository,AuthUseCase,RideUseCase,DriverUseCase,AdminUseCase,FareUseCase,AuditUseCase)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_ports.go -package=mocks github.com/sakai/backend/internal/domain UserRepository,TokenRepository,RideRepository,DriverRepository,AdminRepository,FareRepository,AuditRepository,IncidentRepository,SystemMetricsRepository,AuthUseCase,RideUseCase,DriverUseCase,AdminUseCase,FareUseCase,AuditUseCase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/sakai/backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
}

// CreateWithTokens mocks base method.
func (m *MockUserRepository) CreateWithTokens(ctx context.Context, user *domain.User, refreshToken string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTokens", ctx, user, refreshToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTokens indicates an expected call of CreateWithTokens.
func (mr *MockUserRepositoryMockRecorder) CreateWithTokens(ctx, user, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTokens", reflect.TypeOf((*MockUserRepository)(nil).CreateWithTokens), ctx, user, refreshToken, expiresAt)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(ctx context.Context, email string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// MockTokenRepository is a mock of TokenRepository interface.
type MockTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockTokenRepositoryMockRecorder is the mock recorder for MockTokenRepository.
type MockTokenRepositoryMockRecorder struct {
	mock *MockTokenRepository
}

// NewMockTokenRepository creates a new mock instance.
func NewMockTokenRepository(ctrl *gomock.Controller) *MockTokenRepository {
	mock := &MockTokenRepository{ctrl: ctrl}
	mock.recorder = &MockTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepository) EXPECT() *MockTokenRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockTokenRepository) Delete(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTokenRepositoryMockRecorder) Delete(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTokenRepository)(nil).Delete), ctx, token)
}

// GetUserID mocks base method.
func (m *MockTokenRepository) GetUserID(ctx context.Context, token string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockTokenRepositoryMockRecorder) GetUserID(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockTokenRepository)(nil).GetUserID), ctx, token)
}

// Rotate mocks base method.
func (m *MockTokenRepository) Rotate(ctx context.Context, oldToken, newToken string, userID uuid.UUID, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, oldToken, newToken, userID, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rotate indicates an expected call of Rotate.
func (mr *MockTokenRepositoryMockRecorder) Rotate(ctx, oldToken, newToken, userID, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockTokenRepository)(nil).Rotate), ctx, oldToken, newToken, userID, expiresAt)
}

// Store mocks base method.
func (m *MockTokenRepository) Store(ctx context.Context, userID uuid.UUID, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTokenRepositoryMockRecorder) Store(ctx, userID, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTokenRepository)(nil).Store), ctx, userID, token, expiresAt)
}

// MockRideRepository is a mock of RideRepository interface.
type MockRideRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRideRepositoryMockRecorder
	isgomock struct{}
}

// MockRideRepositoryMockRecorder is the mock recorder for MockRideRepository.
type MockRideRepositoryMockRecorder struct {
	mock *MockRideRepository
}

// NewMockRideRepository creates a new mock instance.
func NewMockRideRepository(ctrl *gomock.Controller) *MockRideRepository {
	mock := &MockRideRepository{ctrl: ctrl}
	mock.recorder = &MockRideRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideRepository) EXPECT() *MockRideRepositoryMockRecorder {
	return m.recorder
}

// AssignDriver mocks base method.
func (m *MockRideRepository) AssignDriver(ctx context.Context, rideID, driverID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDriver", ctx, rideID, driverID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDriver indicates an expected call of AssignDriver.
func (mr *MockRideRepositoryMockRecorder) AssignDriver(ctx, rideID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDriver", reflect.TypeOf((*MockRideRepository)(nil).AssignDriver), ctx, rideID, driverID)
}

// CancelExpiredOffers mocks base method.
func (m *MockRideRepository) CancelExpiredOffers(ctx context.Context, timeout time.Duration) ([]domain.ExpiredOffer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelExpiredOffers", ctx, timeout)
	ret0, _ := ret[0].([]domain.ExpiredOffer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelExpiredOffers indicates an expected call of CancelExpiredOffers.
func (mr *MockRideRepositoryMockRecorder) CancelExpiredOffers(ctx, timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelExpiredOffers", reflect.TypeOf((*MockRideRepository)(nil).CancelExpiredOffers), ctx, timeout)
}

// ClearDriver mocks base method.
func (m *MockRideRepository) ClearDriver(ctx context.Context, rideID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearDriver", ctx, rideID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearDriver indicates an expected call of ClearDriver.
func (mr *MockRideRepositoryMockRecorder) ClearDriver(ctx, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearDriver", reflect.TypeOf((*MockRideRepository)(nil).ClearDriver), ctx, rideID)
}

// Create mocks base method.
func (m *MockRideRepository) Create(ctx context.Context, ride *domain.Ride) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ride)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRideRepositoryMockRecorder) Create(ctx, ride any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRideRepository)(nil).Create), ctx, ride)
}

// GetActiveByDriverID mocks base method.
func (m *MockRideRepository) GetActiveByDriverID(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByDriverID", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByDriverID indicates an expected call of GetActiveByDriverID.
func (mr *MockRideRepositoryMockRecorder) GetActiveByDriverID(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByDriverID", reflect.TypeOf((*MockRideRepository)(nil).GetActiveByDriverID), ctx, driverID)
}

// GetActiveByPassengerID mocks base method.
func (m *MockRideRepository) GetActiveByPassengerID(ctx context.Context, passengerID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveByPassengerID", ctx, passengerID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveByPassengerID indicates an expected call of GetActiveByPassengerID.
func (mr *MockRideRepositoryMockRecorder) GetActiveByPassengerID(ctx, passengerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveByPassengerID", reflect.TypeOf((*MockRideRepository)(nil).GetActiveByPassengerID), ctx, passengerID)
}

// GetByID mocks base method.
func (m *MockRideRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRideRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRideRepository)(nil).GetByID), ctx, id)
}

// GetByIdempotencyKey mocks base method.
func (m *MockRideRepository) GetByIdempotencyKey(ctx context.Context, key string) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIdempotencyKey", ctx, key)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIdempotencyKey indicates an expected call of GetByIdempotencyKey.
func (mr *MockRideRepositoryMockRecorder) GetByIdempotencyKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIdempotencyKey", reflect.TypeOf((*MockRideRepository)(nil).GetByIdempotencyKey), ctx, key)
}

// SetCancelled mocks base method.
func (m *MockRideRepository) SetCancelled(ctx context.Context, id uuid.UUID, by domain.CancelledBy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCancelled", ctx, id, by)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCancelled indicates an expected call of SetCancelled.
func (mr *MockRideRepositoryMockRecorder) SetCancelled(ctx, id, by any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancelled", reflect.TypeOf((*MockRideRepository)(nil).SetCancelled), ctx, id, by)
}

// UpdateStatus mocks base method.
func (m *MockRideRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.RideStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRideRepositoryMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRideRepository)(nil).UpdateStatus), ctx, id, status)
}

// MockDriverRepository is a mock of DriverRepository interface.
type MockDriverRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDriverRepositoryMockRecorder
	isgomock struct{}
}

// MockDriverRepositoryMockRecorder is the mock recorder for MockDriverRepository.
type MockDriverRepositoryMockRecorder struct {
	mock *MockDriverRepository
}

// NewMockDriverRepository creates a new mock instance.
func NewMockDriverRepository(ctrl *gomock.Controller) *MockDriverRepository {
	mock := &MockDriverRepository{ctrl: ctrl}
	mock.recorder = &MockDriverRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverRepository) EXPECT() *MockDriverRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDriverRepository) Create(ctx context.Context, driver *domain.Driver) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, driver)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDriverRepositoryMockRecorder) Create(ctx, driver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriverRepository)(nil).Create), ctx, driver)
}

// FindNearbyOnline mocks base method.
func (m *MockDriverRepository) FindNearbyOnline(ctx context.Context, origin domain.LatLng, radiusMeters float64) ([]*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindNearbyOnline", ctx, origin, radiusMeters)
	ret0, _ := ret[0].([]*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindNearbyOnline indicates an expected call of FindNearbyOnline.
func (mr *MockDriverRepositoryMockRecorder) FindNearbyOnline(ctx, origin, radiusMeters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindNearbyOnline", reflect.TypeOf((*MockDriverRepository)(nil).FindNearbyOnline), ctx, origin, radiusMeters)
}

// GetByUserID mocks base method.
func (m *MockDriverRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.Driver, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Driver)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockDriverRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockDriverRepository)(nil).GetByUserID), ctx, userID)
}

// UpdateLocation mocks base method.
func (m *MockDriverRepository) UpdateLocation(ctx context.Context, userID uuid.UUID, loc domain.DriverLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, userID, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockDriverRepositoryMockRecorder) UpdateLocation(ctx, userID, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockDriverRepository)(nil).UpdateLocation), ctx, userID, loc)
}

// UpdateStatus mocks base method.
func (m *MockDriverRepository) UpdateStatus(ctx context.Context, userID uuid.UUID, status domain.DriverStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockDriverRepositoryMockRecorder) UpdateStatus(ctx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockDriverRepository)(nil).UpdateStatus), ctx, userID, status)
}

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// GetAdmins mocks base method.
func (m *MockAdminRepository) GetAdmins(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdmins", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdmins indicates an expected call of GetAdmins.
func (mr *MockAdminRepositoryMockRecorder) GetAdmins(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdmins", reflect.TypeOf((*MockAdminRepository)(nil).GetAdmins), ctx)
}

// GetCommissionSettings mocks base method.
func (m *MockAdminRepository) GetCommissionSettings(ctx context.Context) ([]*domain.CommissionSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommissionSettings", ctx)
	ret0, _ := ret[0].([]*domain.CommissionSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommissionSettings indicates an expected call of GetCommissionSettings.
func (mr *MockAdminRepositoryMockRecorder) GetCommissionSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommissionSettings", reflect.TypeOf((*MockAdminRepository)(nil).GetCommissionSettings), ctx)
}

// GetPaymentConfigs mocks base method.
func (m *MockAdminRepository) GetPaymentConfigs(ctx context.Context) ([]*domain.PaymentGatewayConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentConfigs", ctx)
	ret0, _ := ret[0].([]*domain.PaymentGatewayConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentConfigs indicates an expected call of GetPaymentConfigs.
func (mr *MockAdminRepositoryMockRecorder) GetPaymentConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentConfigs", reflect.TypeOf((*MockAdminRepository)(nil).GetPaymentConfigs), ctx)
}

// UpdateAdminStatus mocks base method.
func (m *MockAdminRepository) UpdateAdminStatus(ctx context.Context, id uuid.UUID, status domain.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminStatus indicates an expected call of UpdateAdminStatus.
func (mr *MockAdminRepositoryMockRecorder) UpdateAdminStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminStatus", reflect.TypeOf((*MockAdminRepository)(nil).UpdateAdminStatus), ctx, id, status)
}

// UpdateCommissionSettings mocks base method.
func (m *MockAdminRepository) UpdateCommissionSettings(ctx context.Context, settings *domain.CommissionSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCommissionSettings", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCommissionSettings indicates an expected call of UpdateCommissionSettings.
func (mr *MockAdminRepositoryMockRecorder) UpdateCommissionSettings(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCommissionSettings", reflect.TypeOf((*MockAdminRepository)(nil).UpdateCommissionSettings), ctx, settings)
}

// UpdatePaymentConfig mocks base method.
func (m *MockAdminRepository) UpdatePaymentConfig(ctx context.Context, config *domain.PaymentGatewayConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePaymentConfig indicates an expected call of UpdatePaymentConfig.
func (mr *MockAdminRepositoryMockRecorder) UpdatePaymentConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentConfig", reflect.TypeOf((*MockAdminRepository)(nil).UpdatePaymentConfig), ctx, config)
}

// MockFareRepository is a mock of FareRepository interface.
type MockFareRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFareRepositoryMockRecorder
	isgomock struct{}
}

// MockFareRepositoryMockRecorder is the mock recorder for MockFareRepository.
type MockFareRepositoryMockRecorder struct {
	mock *MockFareRepository
}

// NewMockFareRepository creates a new mock instance.
func NewMockFareRepository(ctrl *gomock.Controller) *MockFareRepository {
	mock := &MockFareRepository{ctrl: ctrl}
	mock.recorder = &MockFareRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFareRepository) EXPECT() *MockFareRepositoryMockRecorder {
	return m.recorder
}

// GetFareConfigs mocks base method.
func (m *MockFareRepository) GetFareConfigs(ctx context.Context) ([]*domain.FareConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFareConfigs", ctx)
	ret0, _ := ret[0].([]*domain.FareConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFareConfigs indicates an expected call of GetFareConfigs.
func (mr *MockFareRepositoryMockRecorder) GetFareConfigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFareConfigs", reflect.TypeOf((*MockFareRepository)(nil).GetFareConfigs), ctx)
}

// GetSurgeConfig mocks base method.
func (m *MockFareRepository) GetSurgeConfig(ctx context.Context) (*domain.SurgeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSurgeConfig", ctx)
	ret0, _ := ret[0].(*domain.SurgeConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSurgeConfig indicates an expected call of GetSurgeConfig.
func (mr *MockFareRepositoryMockRecorder) GetSurgeConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSurgeConfig", reflect.TypeOf((*MockFareRepository)(nil).GetSurgeConfig), ctx)
}

// UpdateFareConfig mocks base method.
func (m *MockFareRepository) UpdateFareConfig(ctx context.Context, config *domain.FareConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFareConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFareConfig indicates an expected call of UpdateFareConfig.
func (mr *MockFareRepositoryMockRecorder) UpdateFareConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFareConfig", reflect.TypeOf((*MockFareRepository)(nil).UpdateFareConfig), ctx, config)
}

// UpdateSurgeConfig mocks base method.
func (m *MockFareRepository) UpdateSurgeConfig(ctx context.Context, config *domain.SurgeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSurgeConfig", ctx, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSurgeConfig indicates an expected call of UpdateSurgeConfig.
func (mr *MockFareRepositoryMockRecorder) UpdateSurgeConfig(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSurgeConfig", reflect.TypeOf((*MockFareRepository)(nil).UpdateSurgeConfig), ctx, config)
}

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockAuditRepository) List(ctx context.Context, query domain.AuditQuery) ([]*domain.AuditLogEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].([]*domain.AuditLogEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAuditRepositoryMockRecorder) List(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAuditRepository)(nil).List), ctx, query)
}

// Store mocks base method.
func (m *MockAuditRepository) Store(ctx context.Context, entry *domain.AuditLogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockAuditRepositoryMockRecorder) Store(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockAuditRepository)(nil).Store), ctx, entry)
}

// MockIncidentRepository is a mock of IncidentRepository interface.
type MockIncidentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIncidentRepositoryMockRecorder
	isgomock struct{}
}

// MockIncidentRepositoryMockRecorder is the mock recorder for MockIncidentRepository.
type MockIncidentRepositoryMockRecorder struct {
	mock *MockIncidentRepository
}

// NewMockIncidentRepository creates a new mock instance.
func NewMockIncidentRepository(ctrl *gomock.Controller) *MockIncidentRepository {
	mock := &MockIncidentRepository{ctrl: ctrl}
	mock.recorder = &MockIncidentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIncidentRepository) EXPECT() *MockIncidentRepositoryMockRecorder {
	return m.recorder
}

// GetIncidentByID mocks base method.
func (m *MockIncidentRepository) GetIncidentByID(ctx context.Context, id uuid.UUID) (*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentByID", ctx, id)
	ret0, _ := ret[0].(*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentByID indicates an expected call of GetIncidentByID.
func (mr *MockIncidentRepositoryMockRecorder) GetIncidentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentByID", reflect.TypeOf((*MockIncidentRepository)(nil).GetIncidentByID), ctx, id)
}

// ListIncidents mocks base method.
func (m *MockIncidentRepository) ListIncidents(ctx context.Context, status *string) ([]*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, status)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockIncidentRepositoryMockRecorder) ListIncidents(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockIncidentRepository)(nil).ListIncidents), ctx, status)
}

// UpdateIncident mocks base method.
func (m *MockIncidentRepository) UpdateIncident(ctx context.Context, id uuid.UUID, status, notes string, assignedTo *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIncident", ctx, id, status, notes, assignedTo)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIncident indicates an expected call of UpdateIncident.
func (mr *MockIncidentRepositoryMockRecorder) UpdateIncident(ctx, id, status, notes, assignedTo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIncident", reflect.TypeOf((*MockIncidentRepository)(nil).UpdateIncident), ctx, id, status, notes, assignedTo)
}

// MockSystemMetricsRepository is a mock of SystemMetricsRepository interface.
type MockSystemMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemMetricsRepositoryMockRecorder is the mock recorder for MockSystemMetricsRepository.
type MockSystemMetricsRepositoryMockRecorder struct {
	mock *MockSystemMetricsRepository
}

// NewMockSystemMetricsRepository creates a new mock instance.
func NewMockSystemMetricsRepository(ctrl *gomock.Controller) *MockSystemMetricsRepository {
	mock := &MockSystemMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockSystemMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemMetricsRepository) EXPECT() *MockSystemMetricsRepositoryMockRecorder {
	return m.recorder
}

// GetDashboardMetrics mocks base method.
func (m *MockSystemMetricsRepository) GetDashboardMetrics(ctx context.Context) (*domain.DashboardMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardMetrics", ctx)
	ret0, _ := ret[0].(*domain.DashboardMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardMetrics indicates an expected call of GetDashboardMetrics.
func (mr *MockSystemMetricsRepositoryMockRecorder) GetDashboardMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardMetrics", reflect.TypeOf((*MockSystemMetricsRepository)(nil).GetDashboardMetrics), ctx)
}

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
	isgomock struct{}
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockAuthUseCase) GetUserByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAuthUseCaseMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAuthUseCase)(nil).GetUserByID), ctx, id)
}

// Login mocks base method.
func (m *MockAuthUseCase) Login(ctx context.Context, email, password string) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthUseCaseMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthUseCase)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockAuthUseCase) Logout(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthUseCaseMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthUseCase)(nil).Logout), ctx, refreshToken)
}

// Refresh mocks base method.
func (m *MockAuthUseCase) Refresh(ctx context.Context, refreshToken string) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthUseCaseMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuthUseCase)(nil).Refresh), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockAuthUseCase) Register(ctx context.Context, name, email, password string, role domain.UserRole, vehicle *domain.Vehicle) (*domain.AuthOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, name, email, password, role, vehicle)
	ret0, _ := ret[0].(*domain.AuthOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthUseCaseMockRecorder) Register(ctx, name, email, password, role, vehicle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthUseCase)(nil).Register), ctx, name, email, password, role, vehicle)
}

// MockRideUseCase is a mock of RideUseCase interface.
type MockRideUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRideUseCaseMockRecorder
	isgomock struct{}
}

// MockRideUseCaseMockRecorder is the mock recorder for MockRideUseCase.
type MockRideUseCaseMockRecorder struct {
	mock *MockRideUseCase
}

// NewMockRideUseCase creates a new mock instance.
func NewMockRideUseCase(ctrl *gomock.Controller) *MockRideUseCase {
	mock := &MockRideUseCase{ctrl: ctrl}
	mock.recorder = &MockRideUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRideUseCase) EXPECT() *MockRideUseCaseMockRecorder {
	return m.recorder
}

// Accept mocks base method.
func (m *MockRideUseCase) Accept(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accept", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Accept indicates an expected call of Accept.
func (mr *MockRideUseCaseMockRecorder) Accept(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accept", reflect.TypeOf((*MockRideUseCase)(nil).Accept), ctx, driverID, rideID)
}

// Arrive mocks base method.
func (m *MockRideUseCase) Arrive(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Arrive", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Arrive indicates an expected call of Arrive.
func (mr *MockRideUseCaseMockRecorder) Arrive(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Arrive", reflect.TypeOf((*MockRideUseCase)(nil).Arrive), ctx, driverID, rideID)
}

// Cancel mocks base method.
func (m *MockRideUseCase) Cancel(ctx context.Context, userID uuid.UUID, role domain.UserRole, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, userID, role, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRideUseCaseMockRecorder) Cancel(ctx, userID, role, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRideUseCase)(nil).Cancel), ctx, userID, role, rideID)
}

// Complete mocks base method.
func (m *MockRideUseCase) Complete(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockRideUseCaseMockRecorder) Complete(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockRideUseCase)(nil).Complete), ctx, driverID, rideID)
}

// Decline mocks base method.
func (m *MockRideUseCase) Decline(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decline", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decline indicates an expected call of Decline.
func (mr *MockRideUseCaseMockRecorder) Decline(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decline", reflect.TypeOf((*MockRideUseCase)(nil).Decline), ctx, driverID, rideID)
}

// GetActive mocks base method.
func (m *MockRideUseCase) GetActive(ctx context.Context, userID uuid.UUID, role domain.UserRole) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx, userID, role)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockRideUseCaseMockRecorder) GetActive(ctx, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockRideUseCase)(nil).GetActive), ctx, userID, role)
}

// GetByID mocks base method.
func (m *MockRideUseCase) GetByID(ctx context.Context, userID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRideUseCaseMockRecorder) GetByID(ctx, userID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRideUseCase)(nil).GetByID), ctx, userID, rideID)
}

// RequestRide mocks base method.
func (m *MockRideUseCase) RequestRide(ctx context.Context, passengerID uuid.UUID, origin, destination domain.LatLng, originAddr, destAddr, notes, idempotencyKey string) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestRide", ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestRide indicates an expected call of RequestRide.
func (mr *MockRideUseCaseMockRecorder) RequestRide(ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestRide", reflect.TypeOf((*MockRideUseCase)(nil).RequestRide), ctx, passengerID, origin, destination, originAddr, destAddr, notes, idempotencyKey)
}

// Start mocks base method.
func (m *MockRideUseCase) Start(ctx context.Context, driverID, rideID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, driverID, rideID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockRideUseCaseMockRecorder) Start(ctx, driverID, rideID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRideUseCase)(nil).Start), ctx, driverID, rideID)
}

// MockDriverUseCase is a mock of DriverUseCase interface.
type MockDriverUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDriverUseCaseMockRecorder
	isgomock struct{}
}

// MockDriverUseCaseMockRecorder is the mock recorder for MockDriverUseCase.
type MockDriverUseCaseMockRecorder struct {
	mock *MockDriverUseCase
}

// NewMockDriverUseCase creates a new mock instance.
func NewMockDriverUseCase(ctrl *gomock.Controller) *MockDriverUseCase {
	mock := &MockDriverUseCase{ctrl: ctrl}
	mock.recorder = &MockDriverUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverUseCase) EXPECT() *MockDriverUseCaseMockRecorder {
	return m.recorder
}

// GetActiveRide mocks base method.
func (m *MockDriverUseCase) GetActiveRide(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveRide", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveRide indicates an expected call of GetActiveRide.
func (mr *MockDriverUseCaseMockRecorder) GetActiveRide(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveRide", reflect.TypeOf((*MockDriverUseCase)(nil).GetActiveRide), ctx, driverID)
}

// GetIncomingRide mocks base method.
func (m *MockDriverUseCase) GetIncomingRide(ctx context.Context, driverID uuid.UUID) (*domain.Ride, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncomingRide", ctx, driverID)
	ret0, _ := ret[0].(*domain.Ride)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncomingRide indicates an expected call of GetIncomingRide.
func (mr *MockDriverUseCaseMockRecorder) GetIncomingRide(ctx, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncomingRide", reflect.TypeOf((*MockDriverUseCase)(nil).GetIncomingRide), ctx, driverID)
}

// SetStatus mocks base method.
func (m *MockDriverUseCase) SetStatus(ctx context.Context, driverID uuid.UUID, status domain.DriverStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, driverID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockDriverUseCaseMockRecorder) SetStatus(ctx, driverID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockDriverUseCase)(nil).SetStatus), ctx, driverID, status)
}

// UpdateLocation mocks base method.
func (m *MockDriverUseCase) UpdateLocation(ctx context.Context, driverID uuid.UUID, loc domain.DriverLocation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLocation", ctx, driverID, loc)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLocation indicates an expected call of UpdateLocation.
func (mr *MockDriverUseCaseMockRecorder) UpdateLocation(ctx, driverID, loc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLocation", reflect.TypeOf((*MockDriverUseCase)(nil).UpdateLocation), ctx, driverID, loc)
}

// MockAdminUseCase is a mock of AdminUseCase interface.
type MockAdminUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUseCaseMockRecorder
	isgomock struct{}
}

// MockAdminUseCaseMockRecorder is the mock recorder for MockAdminUseCase.
type MockAdminUseCaseMockRecorder struct {
	mock *MockAdminUseCase
}

// NewMockAdminUseCase creates a new mock instance.
func NewMockAdminUseCase(ctrl *gomock.Controller) *MockAdminUseCase {
	mock := &MockAdminUseCase{ctrl: ctrl}
	mock.recorder = &MockAdminUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUseCase) EXPECT() *MockAdminUseCaseMockRecorder {
	return m.recorder
}

// CreateAdmin mocks base method.
func (m *MockAdminUseCase) CreateAdmin(ctx context.Context, actorID uuid.UUID, name, email, password string, role domain.UserRole) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdmin", ctx, actorID, name, email, password, role)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdmin indicates an expected call of CreateAdmin.
func (mr *MockAdminUseCaseMockRecorder) CreateAdmin(ctx, actorID, name, email, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdmin", reflect.TypeOf((*MockAdminUseCase)(nil).CreateAdmin), ctx, actorID, name, email, password, role)
}

// GetDashboard mocks base method.
func (m *MockAdminUseCase) GetDashboard(ctx context.Context) (*domain.DashboardMetrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx)
	ret0, _ := ret[0].(*domain.DashboardMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockAdminUseCaseMockRecorder) GetDashboard(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockAdminUseCase)(nil).GetDashboard), ctx)
}

// ListAdmins mocks base method.
func (m *MockAdminUseCase) ListAdmins(ctx context.Context) ([]*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdmins", ctx)
	ret0, _ := ret[0].([]*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdmins indicates an expected call of ListAdmins.
func (mr *MockAdminUseCaseMockRecorder) ListAdmins(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdmins", reflect.TypeOf((*MockAdminUseCase)(nil).ListAdmins), ctx)
}

// ListIncidents mocks base method.
func (m *MockAdminUseCase) ListIncidents(ctx context.Context, status *string) ([]*domain.Incident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncidents", ctx, status)
	ret0, _ := ret[0].([]*domain.Incident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncidents indicates an expected call of ListIncidents.
func (mr *MockAdminUseCaseMockRecorder) ListIncidents(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncidents", reflect.TypeOf((*MockAdminUseCase)(nil).ListIncidents), ctx, status)
}

// ResolveIncident mocks base method.
func (m *MockAdminUseCase) ResolveIncident(ctx context.Context, actorID, incidentID uuid.UUID, notes string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIncident", ctx, actorID, incidentID, notes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveIncident indicates an expected call of ResolveIncident.
func (mr *MockAdminUseCaseMockRecorder) ResolveIncident(ctx, actorID, incidentID, notes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIncident", reflect.TypeOf((*MockAdminUseCase)(nil).ResolveIncident), ctx, actorID, incidentID, notes)
}

// UpdateAdminStatus mocks base method.
func (m *MockAdminUseCase) UpdateAdminStatus(ctx context.Context, actorID, targetID uuid.UUID, status domain.UserRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminStatus", ctx, actorID, targetID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminStatus indicates an expected call of UpdateAdminStatus.
func (mr *MockAdminUseCaseMockRecorder) UpdateAdminStatus(ctx, actorID, targetID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminStatus", reflect.TypeOf((*MockAdminUseCase)(nil).UpdateAdminStatus), ctx, actorID, targetID, status)
}

// MockFareUseCase is a mock of FareUseCase interface.
type MockFareUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockFareUseCaseMockRecorder
	isgomock struct{}
}

// MockFareUseCaseMockRecorder is the mock recorder for MockFareUseCase.
type MockFareUseCaseMockRecorder struct {
	mock *MockFareUseCase
}

// NewMockFareUseCase creates a new mock instance.
func NewMockFareUseCase(ctrl *gomock.Controller) *MockFareUseCase {
	mock := &MockFareUseCase{ctrl: ctrl}
	mock.recorder = &MockFareUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFareUseCase) EXPECT() *MockFareUseCaseMockRecorder {
	return m.recorder
}

// GetConfig mocks base method.
func (m *MockFareUseCase) GetConfig(ctx context.Context) ([]*domain.FareConfig, *domain.SurgeConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", ctx)
	ret0, _ := ret[0].([]*domain.FareConfig)
	ret1, _ := ret[1].(*domain.SurgeConfig)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetConfig indicates an expected call of GetConfig.
func (mr *MockFareUseCaseMockRecorder) GetConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockFareUseCase)(nil).GetConfig), ctx)
}

// SimulateFare mocks base method.
func (m *MockFareUseCase) SimulateFare(ctx context.Context, vehicleType string, origin, destination domain.LatLng) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SimulateFare", ctx, vehicleType, origin, destination)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SimulateFare indicates an expected call of SimulateFare.
func (mr *MockFareUseCaseMockRecorder) SimulateFare(ctx, vehicleType, origin, destination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SimulateFare", reflect.TypeOf((*MockFareUseCase)(nil).SimulateFare), ctx, vehicleType, origin, destination)
}

// UpdateFares mocks base method.
func (m *MockFareUseCase) UpdateFares(ctx context.Context, actorID uuid.UUID, configs []*domain.FareConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFares", ctx, actorID, configs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFares indicates an expected call of UpdateFares.
func (mr *MockFareUseCaseMockRecorder) UpdateFares(ctx, actorID, configs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFares", reflect.TypeOf((*MockFareUseCase)(nil).UpdateFares), ctx, actorID, configs)
}

// UpdateSurge mocks base method.
func (m *MockFareUseCase) UpdateSurge(ctx context.Context, actorID uuid.UUID, config *domain.SurgeConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSurge", ctx, actorID, config)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSurge indicates an expected call of UpdateSurge.
func (mr *MockFareUseCaseMockRecorder) UpdateSurge(ctx, actorID, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSurge", reflect.TypeOf((*MockFareUseCase)(nil).UpdateSurge), ctx, actorID, config)
}

// MockAuditUseCase is a mock of AuditUseCase interface.
type MockAuditUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuditUseCaseMockRecorder
	isgomock struct{}
}

// MockAuditUseCaseMockRecorder is the mock recorder for MockAuditUseCase.
type MockAuditUseCaseMockRecorder struct {
	mock *MockAuditUseCase
}

// NewMockAuditUseCase creates a new mock instance.
func NewMockAuditUseCase(ctrl *gomock.Controller) *MockAuditUseCase {
	mock := &MockAuditUseCase{ctrl: ctrl}
	mock.recorder = &MockAuditUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditUseCase) EXPECT() *MockAuditUseCaseMockRecorder {
	return m.recorder
}

// GetLogs mocks base method.
func (m *MockAuditUseCase) GetLogs(ctx context.Context, query domain.AuditQuery) ([]*domain.AuditLogEntry, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, query)
	ret0, _ := ret[0].([]*domain.AuditLogEntry)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockAuditUseCaseMockRecorder) GetLogs(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockAuditUseCase)(nil).GetLogs), ctx, query)
}

// LogAction mocks base method.
func (m *MockAuditUseCase) LogAction(ctx context.Context, entry *domain.AuditLogEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAction", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAction indicates an expected call of LogAction.
func (mr *MockAuditUseCaseMockRecorder) LogAction(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAction", reflect.TypeOf((*MockAuditUseCase)(nil).LogAction), ctx, entry)
}
