// Mocks generated by Mockito 5.4.6 from annotations
// in passenger/test/promotions_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:built_collection/built_collection.dart' as _i9;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/src/api/users_api.dart' as _i3;
import 'package:sakai_api_client/src/model/add_payment_method_request.dart'
    as _i7;
import 'package:sakai_api_client/src/model/payment_method_details.dart' as _i6;
import 'package:sakai_api_client/src/model/payment_method_list_response.dart'
    as _i8;
import 'package:sakai_api_client/src/model/promotion.dart' as _i10;
import 'package:sakai_api_client/src/model/promotion_validate_request.dart'
    as _i11;
import 'package:sakai_api_client/src/model/saved_place.dart' as _i12;
import 'package:sakai_api_client/src/model/saved_place_create_request.dart'
    as _i13;
import 'package:sakai_api_client/src/model/user_profile.dart' as _i14;
import 'package:sakai_api_client/src/model/user_rating_response.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UsersApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersApi extends _i1.Mock implements _i3.UsersApi {
  MockUsersApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<_i5.UserRatingResponse>> getUserRating({
    required String? userId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRating, [], {
              #userId: userId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i5.UserRatingResponse>>.value(
              _FakeResponse_0<_i5.UserRatingResponse>(
                this,
                Invocation.method(#getUserRating, [], {
                  #userId: userId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<_i5.UserRatingResponse>>);

  @override
  _i4.Future<_i2.Response<_i6.PaymentMethodDetails>> paymentMethodsAdd({
    required _i7.AddPaymentMethodRequest? addPaymentMethodRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsAdd, [], {
              #addPaymentMethodRequest: addPaymentMethodRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i6.PaymentMethodDetails>>.value(
                  _FakeResponse_0<_i6.PaymentMethodDetails>(
                    this,
                    Invocation.method(#paymentMethodsAdd, [], {
                      #addPaymentMethodRequest: addPaymentMethodRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i6.PaymentMethodDetails>>);

  @override
  _i4.Future<_i2.Response<_i8.PaymentMethodListResponse>> paymentMethodsList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i8.PaymentMethodListResponse>>.value(
                  _FakeResponse_0<_i8.PaymentMethodListResponse>(
                    this,
                    Invocation.method(#paymentMethodsList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i8.PaymentMethodListResponse>>);

  @override
  _i4.Future<_i2.Response<void>> paymentMethodsRemove({
    required String? paymentMethodId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsRemove, [], {
              #paymentMethodId: paymentMethodId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#paymentMethodsRemove, [], {
                  #paymentMethodId: paymentMethodId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i6.PaymentMethodDetails>> paymentMethodsSetDefault({
    required String? paymentMethodId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsSetDefault, [], {
              #paymentMethodId: paymentMethodId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i6.PaymentMethodDetails>>.value(
                  _FakeResponse_0<_i6.PaymentMethodDetails>(
                    this,
                    Invocation.method(#paymentMethodsSetDefault, [], {
                      #paymentMethodId: paymentMethodId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i6.PaymentMethodDetails>>);

  @override
  _i4.Future<_i2.Response<_i9.BuiltList<_i10.Promotion>>> promotionsList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#promotionsList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i9.BuiltList<_i10.Promotion>>>.value(
                  _FakeResponse_0<_i9.BuiltList<_i10.Promotion>>(
                    this,
                    Invocation.method(#promotionsList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i9.BuiltList<_i10.Promotion>>>);

  @override
  _i4.Future<_i2.Response<_i10.Promotion>> promotionsValidate({
    required _i11.PromotionValidateRequest? promotionValidateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#promotionsValidate, [], {
              #promotionValidateRequest: promotionValidateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i10.Promotion>>.value(
              _FakeResponse_0<_i10.Promotion>(
                this,
                Invocation.method(#promotionsValidate, [], {
                  #promotionValidateRequest: promotionValidateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<_i10.Promotion>>);

  @override
  _i4.Future<_i2.Response<_i12.SavedPlace>> savedPlacesCreate({
    required _i13.SavedPlaceCreateRequest? savedPlaceCreateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesCreate, [], {
              #savedPlaceCreateRequest: savedPlaceCreateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i12.SavedPlace>>.value(
              _FakeResponse_0<_i12.SavedPlace>(
                this,
                Invocation.method(#savedPlacesCreate, [], {
                  #savedPlaceCreateRequest: savedPlaceCreateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<_i12.SavedPlace>>);

  @override
  _i4.Future<_i2.Response<void>> savedPlacesDelete({
    required String? placeId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesDelete, [], {
              #placeId: placeId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#savedPlacesDelete, [], {
                  #placeId: placeId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i9.BuiltList<_i12.SavedPlace>>> savedPlacesList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i9.BuiltList<_i12.SavedPlace>>>.value(
                  _FakeResponse_0<_i9.BuiltList<_i12.SavedPlace>>(
                    this,
                    Invocation.method(#savedPlacesList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i9.BuiltList<_i12.SavedPlace>>>);

  @override
  _i4.Future<_i2.Response<_i14.UserProfile>> usersGetMe({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#usersGetMe, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i14.UserProfile>>.value(
              _FakeResponse_0<_i14.UserProfile>(
                this,
                Invocation.method(#usersGetMe, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<_i14.UserProfile>>);

  @override
  _i4.Future<_i2.Response<void>> usersMeDelete({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#usersMeDelete, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#usersMeDelete, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);
}
