// Mocks generated by Mockito 5.4.6 from annotations
// in passenger/test/sos_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/sakai_api_client.dart' as _i4;
import 'package:sakai_api_client/src/model/add_ride_tip_request.dart' as _i7;
import 'package:sakai_api_client/src/model/cancel_request.dart' as _i13;
import 'package:sakai_api_client/src/model/incident.dart' as _i3;
import 'package:sakai_api_client/src/model/payment_process_request.dart'
    as _i10;
import 'package:sakai_api_client/src/model/payment_response.dart' as _i9;
import 'package:sakai_api_client/src/model/rating_response.dart' as _i18;
import 'package:sakai_api_client/src/model/receipt_response.dart' as _i8;
import 'package:sakai_api_client/src/model/ride_arrive_request.dart' as _i12;
import 'package:sakai_api_client/src/model/ride_complete_request.dart' as _i14;
import 'package:sakai_api_client/src/model/ride_request_body.dart' as _i16;
import 'package:sakai_api_client/src/model/ride_response.dart' as _i11;
import 'package:sakai_api_client/src/model/submit_rating_request.dart' as _i19;
import 'package:sakai_api_client/src/model/tip_response.dart' as _i6;
import 'package:sakai_api_client/src/model/trigger_sos_request.dart' as _i17;
import 'package:sakai_api_client/src/model/user_ride_list_response.dart'
    as _i15;
import 'package:sakai_shared/repositories/sos_repository.dart' as _i20;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIncident_1 extends _i1.SmartFake implements _i3.Incident {
  _FakeIncident_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RidesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRidesApi extends _i1.Mock implements _i4.RidesApi {
  MockRidesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Response<_i6.TipResponse>> addRideTip({
    required String? rideId,
    required _i7.AddRideTipRequest? addRideTipRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRideTip, [], {
              #rideId: rideId,
              #addRideTipRequest: addRideTipRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i6.TipResponse>>.value(
              _FakeResponse_0<_i6.TipResponse>(
                this,
                Invocation.method(#addRideTip, [], {
                  #rideId: rideId,
                  #addRideTipRequest: addRideTipRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i6.TipResponse>>);

  @override
  _i5.Future<_i2.Response<_i8.ReceiptResponse>> getRideReceipt({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRideReceipt, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i8.ReceiptResponse>>.value(
              _FakeResponse_0<_i8.ReceiptResponse>(
                this,
                Invocation.method(#getRideReceipt, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i8.ReceiptResponse>>);

  @override
  _i5.Future<_i2.Response<_i9.PaymentResponse>> paymentProcess({
    required String? idempotencyKey,
    required _i10.PaymentProcessRequest? paymentProcessRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentProcess, [], {
              #idempotencyKey: idempotencyKey,
              #paymentProcessRequest: paymentProcessRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i9.PaymentResponse>>.value(
              _FakeResponse_0<_i9.PaymentResponse>(
                this,
                Invocation.method(#paymentProcess, [], {
                  #idempotencyKey: idempotencyKey,
                  #paymentProcessRequest: paymentProcessRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i9.PaymentResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideAccept({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideAccept, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideAccept, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideArrive({
    required String? rideId,
    required _i12.RideArriveRequest? rideArriveRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideArrive, [], {
              #rideId: rideId,
              #rideArriveRequest: rideArriveRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideArrive, [], {
                  #rideId: rideId,
                  #rideArriveRequest: rideArriveRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideCancel({
    required String? rideId,
    _i13.CancelRequest? cancelRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideCancel, [], {
              #rideId: rideId,
              #cancelRequest: cancelRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideCancel, [], {
                  #rideId: rideId,
                  #cancelRequest: cancelRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideComplete({
    required String? rideId,
    required _i14.RideCompleteRequest? rideCompleteRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideComplete, [], {
              #rideId: rideId,
              #rideCompleteRequest: rideCompleteRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideComplete, [], {
                  #rideId: rideId,
                  #rideCompleteRequest: rideCompleteRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideDecline({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideDecline, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideDecline, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideGet({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideGet, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideGet, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideGetActive({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideGetActive, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideGetActive, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i15.UserRideListResponse>> rideList({
    int? page = 1,
    int? limit = 20,
    String? status,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideList, [], {
              #page: page,
              #limit: limit,
              #status: status,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i5.Future<_i2.Response<_i15.UserRideListResponse>>.value(
                  _FakeResponse_0<_i15.UserRideListResponse>(
                    this,
                    Invocation.method(#rideList, [], {
                      #page: page,
                      #limit: limit,
                      #status: status,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Response<_i15.UserRideListResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideRequest({
    required String? idempotencyKey,
    required _i16.RideRequestBody? rideRequestBody,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideRequest, [], {
              #idempotencyKey: idempotencyKey,
              #rideRequestBody: rideRequestBody,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideRequest, [], {
                  #idempotencyKey: idempotencyKey,
                  #rideRequestBody: rideRequestBody,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i11.RideResponse>> rideStart({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideStart, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i11.RideResponse>>.value(
              _FakeResponse_0<_i11.RideResponse>(
                this,
                Invocation.method(#rideStart, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i11.RideResponse>>);

  @override
  _i5.Future<_i2.Response<_i3.Incident>> rideTriggerSOS({
    required String? rideId,
    required _i17.TriggerSOSRequest? triggerSOSRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideTriggerSOS, [], {
              #rideId: rideId,
              #triggerSOSRequest: triggerSOSRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i3.Incident>>.value(
              _FakeResponse_0<_i3.Incident>(
                this,
                Invocation.method(#rideTriggerSOS, [], {
                  #rideId: rideId,
                  #triggerSOSRequest: triggerSOSRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i3.Incident>>);

  @override
  _i5.Future<_i2.Response<_i18.RatingResponse>> submitRating({
    required String? rideId,
    required _i19.SubmitRatingRequest? submitRatingRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitRating, [], {
              #rideId: rideId,
              #submitRatingRequest: submitRatingRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i5.Future<_i2.Response<_i18.RatingResponse>>.value(
              _FakeResponse_0<_i18.RatingResponse>(
                this,
                Invocation.method(#submitRating, [], {
                  #rideId: rideId,
                  #submitRatingRequest: submitRatingRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Response<_i18.RatingResponse>>);
}

/// A class which mocks [SOSRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSOSRepository extends _i1.Mock implements _i20.SOSRepository {
  MockSOSRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Incident> triggerSOS(String? rideId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#triggerSOS, [rideId], {#reason: reason}),
            returnValue: _i5.Future<_i3.Incident>.value(
              _FakeIncident_1(
                this,
                Invocation.method(#triggerSOS, [rideId], {#reason: reason}),
              ),
            ),
          )
          as _i5.Future<_i3.Incident>);

  @override
  _i5.Future<_i3.Incident?> getActiveIncident(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveIncident, [rideId]),
            returnValue: _i5.Future<_i3.Incident?>.value(),
          )
          as _i5.Future<_i3.Incident?>);
}
