// Mocks generated by Mockito 5.4.6 from annotations
// in passenger/test/features/ride_history/ride_history_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/src/api.dart' as _i10;
import 'package:sakai_api_client/src/api/admin_api.dart' as _i4;
import 'package:sakai_api_client/src/api/auth_api.dart' as _i5;
import 'package:sakai_api_client/src/api/driver_api.dart' as _i6;
import 'package:sakai_api_client/src/api/rides_api.dart' as _i7;
import 'package:sakai_api_client/src/api/system_api.dart' as _i8;
import 'package:sakai_api_client/src/api/users_api.dart' as _i9;
import 'package:sakai_api_client/src/model/add_ride_tip_request.dart' as _i13;
import 'package:sakai_api_client/src/model/cancel_request.dart' as _i19;
import 'package:sakai_api_client/src/model/incident.dart' as _i23;
import 'package:sakai_api_client/src/model/payment_process_request.dart'
    as _i16;
import 'package:sakai_api_client/src/model/payment_response.dart' as _i15;
import 'package:sakai_api_client/src/model/rating_response.dart' as _i25;
import 'package:sakai_api_client/src/model/receipt_response.dart' as _i14;
import 'package:sakai_api_client/src/model/ride_arrive_request.dart' as _i18;
import 'package:sakai_api_client/src/model/ride_complete_request.dart' as _i20;
import 'package:sakai_api_client/src/model/ride_request_body.dart' as _i22;
import 'package:sakai_api_client/src/model/ride_response.dart' as _i17;
import 'package:sakai_api_client/src/model/submit_rating_request.dart' as _i26;
import 'package:sakai_api_client/src/model/tip_response.dart' as _i12;
import 'package:sakai_api_client/src/model/trigger_sos_request.dart' as _i24;
import 'package:sakai_api_client/src/model/user_ride_list_response.dart'
    as _i21;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminApi_2 extends _i1.SmartFake implements _i4.AdminApi {
  _FakeAdminApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthApi_3 extends _i1.SmartFake implements _i5.AuthApi {
  _FakeAuthApi_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriverApi_4 extends _i1.SmartFake implements _i6.DriverApi {
  _FakeDriverApi_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRidesApi_5 extends _i1.SmartFake implements _i7.RidesApi {
  _FakeRidesApi_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemApi_6 extends _i1.SmartFake implements _i8.SystemApi {
  _FakeSystemApi_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersApi_7 extends _i1.SmartFake implements _i9.UsersApi {
  _FakeUsersApi_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_8<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SakaiApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSakaiApiClient extends _i1.Mock implements _i10.SakaiApiClient {
  MockSakaiApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.AdminApi getAdminApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminApi, []),
            returnValue: _FakeAdminApi_2(
              this,
              Invocation.method(#getAdminApi, []),
            ),
          )
          as _i4.AdminApi);

  @override
  _i5.AuthApi getAuthApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthApi, []),
            returnValue: _FakeAuthApi_3(
              this,
              Invocation.method(#getAuthApi, []),
            ),
          )
          as _i5.AuthApi);

  @override
  _i6.DriverApi getDriverApi() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverApi, []),
            returnValue: _FakeDriverApi_4(
              this,
              Invocation.method(#getDriverApi, []),
            ),
          )
          as _i6.DriverApi);

  @override
  _i7.RidesApi getRidesApi() =>
      (super.noSuchMethod(
            Invocation.method(#getRidesApi, []),
            returnValue: _FakeRidesApi_5(
              this,
              Invocation.method(#getRidesApi, []),
            ),
          )
          as _i7.RidesApi);

  @override
  _i8.SystemApi getSystemApi() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemApi, []),
            returnValue: _FakeSystemApi_6(
              this,
              Invocation.method(#getSystemApi, []),
            ),
          )
          as _i8.SystemApi);

  @override
  _i9.UsersApi getUsersApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUsersApi, []),
            returnValue: _FakeUsersApi_7(
              this,
              Invocation.method(#getUsersApi, []),
            ),
          )
          as _i9.UsersApi);
}

/// A class which mocks [RidesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockRidesApi extends _i1.Mock implements _i7.RidesApi {
  MockRidesApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Response<_i12.TipResponse>> addRideTip({
    required String? rideId,
    required _i13.AddRideTipRequest? addRideTipRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addRideTip, [], {
              #rideId: rideId,
              #addRideTipRequest: addRideTipRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i12.TipResponse>>.value(
              _FakeResponse_8<_i12.TipResponse>(
                this,
                Invocation.method(#addRideTip, [], {
                  #rideId: rideId,
                  #addRideTipRequest: addRideTipRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i12.TipResponse>>);

  @override
  _i11.Future<_i2.Response<_i14.ReceiptResponse>> getRideReceipt({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRideReceipt, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i14.ReceiptResponse>>.value(
              _FakeResponse_8<_i14.ReceiptResponse>(
                this,
                Invocation.method(#getRideReceipt, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i14.ReceiptResponse>>);

  @override
  _i11.Future<_i2.Response<_i15.PaymentResponse>> paymentProcess({
    required String? idempotencyKey,
    required _i16.PaymentProcessRequest? paymentProcessRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentProcess, [], {
              #idempotencyKey: idempotencyKey,
              #paymentProcessRequest: paymentProcessRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i15.PaymentResponse>>.value(
              _FakeResponse_8<_i15.PaymentResponse>(
                this,
                Invocation.method(#paymentProcess, [], {
                  #idempotencyKey: idempotencyKey,
                  #paymentProcessRequest: paymentProcessRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i15.PaymentResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideAccept({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideAccept, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideAccept, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideArrive({
    required String? rideId,
    required _i18.RideArriveRequest? rideArriveRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideArrive, [], {
              #rideId: rideId,
              #rideArriveRequest: rideArriveRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideArrive, [], {
                  #rideId: rideId,
                  #rideArriveRequest: rideArriveRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideCancel({
    required String? rideId,
    _i19.CancelRequest? cancelRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideCancel, [], {
              #rideId: rideId,
              #cancelRequest: cancelRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideCancel, [], {
                  #rideId: rideId,
                  #cancelRequest: cancelRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideComplete({
    required String? rideId,
    required _i20.RideCompleteRequest? rideCompleteRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideComplete, [], {
              #rideId: rideId,
              #rideCompleteRequest: rideCompleteRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideComplete, [], {
                  #rideId: rideId,
                  #rideCompleteRequest: rideCompleteRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideDecline({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideDecline, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideDecline, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideGet({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideGet, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideGet, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideGetActive({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideGetActive, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideGetActive, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i21.UserRideListResponse>> rideList({
    int? page = 1,
    int? limit = 20,
    String? status,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideList, [], {
              #page: page,
              #limit: limit,
              #status: status,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i21.UserRideListResponse>>.value(
                  _FakeResponse_8<_i21.UserRideListResponse>(
                    this,
                    Invocation.method(#rideList, [], {
                      #page: page,
                      #limit: limit,
                      #status: status,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i21.UserRideListResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideRequest({
    required String? idempotencyKey,
    required _i22.RideRequestBody? rideRequestBody,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideRequest, [], {
              #idempotencyKey: idempotencyKey,
              #rideRequestBody: rideRequestBody,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideRequest, [], {
                  #idempotencyKey: idempotencyKey,
                  #rideRequestBody: rideRequestBody,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i17.RideResponse>> rideStart({
    required String? rideId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideStart, [], {
              #rideId: rideId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i17.RideResponse>>.value(
              _FakeResponse_8<_i17.RideResponse>(
                this,
                Invocation.method(#rideStart, [], {
                  #rideId: rideId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i17.RideResponse>>);

  @override
  _i11.Future<_i2.Response<_i23.Incident>> rideTriggerSOS({
    required String? rideId,
    required _i24.TriggerSOSRequest? triggerSOSRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rideTriggerSOS, [], {
              #rideId: rideId,
              #triggerSOSRequest: triggerSOSRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i23.Incident>>.value(
              _FakeResponse_8<_i23.Incident>(
                this,
                Invocation.method(#rideTriggerSOS, [], {
                  #rideId: rideId,
                  #triggerSOSRequest: triggerSOSRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i23.Incident>>);

  @override
  _i11.Future<_i2.Response<_i25.RatingResponse>> submitRating({
    required String? rideId,
    required _i26.SubmitRatingRequest? submitRatingRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitRating, [], {
              #rideId: rideId,
              #submitRatingRequest: submitRatingRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i25.RatingResponse>>.value(
              _FakeResponse_8<_i25.RatingResponse>(
                this,
                Invocation.method(#submitRating, [], {
                  #rideId: rideId,
                  #submitRatingRequest: submitRatingRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i25.RatingResponse>>);
}
