// Mocks generated by Mockito 5.4.6 from annotations
// in driver/test/ride_history_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:built_collection/built_collection.dart' as _i15;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/src/api/driver_api.dart' as _i3;
import 'package:sakai_api_client/src/model/admin_list_driver_rides200_response.dart'
    as _i5;
import 'package:sakai_api_client/src/model/date.dart' as _i8;
import 'package:sakai_api_client/src/model/driver_document_response.dart'
    as _i6;
import 'package:sakai_api_client/src/model/driver_documents_list_response.dart'
    as _i10;
import 'package:sakai_api_client/src/model/driver_get_earnings200_response.dart'
    as _i7;
import 'package:sakai_api_client/src/model/driver_status_request.dart' as _i12;
import 'package:sakai_api_client/src/model/driver_status_response.dart' as _i11;
import 'package:sakai_api_client/src/model/get_nearby_drivers200_response.dart'
    as _i14;
import 'package:sakai_api_client/src/model/location_update_request.dart'
    as _i13;
import 'package:sakai_api_client/src/model/nearby_driver.dart' as _i16;
import 'package:sakai_api_client/src/model/ride_response.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DriverApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriverApi extends _i1.Mock implements _i3.DriverApi {
  MockDriverApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<_i5.AdminListDriverRides200Response>>
  adminListDriverRides({
    int? page = 1,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#adminListDriverRides, [], {
              #page: page,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<_i5.AdminListDriverRides200Response>
                >.value(
                  _FakeResponse_0<_i5.AdminListDriverRides200Response>(
                    this,
                    Invocation.method(#adminListDriverRides, [], {
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i5.AdminListDriverRides200Response>>);

  @override
  _i4.Future<_i2.Response<_i6.DriverDocumentResponse>> driverGetDocumentStatus({
    required String? documentId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetDocumentStatus, [], {
              #documentId: documentId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i6.DriverDocumentResponse>>.value(
                  _FakeResponse_0<_i6.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverGetDocumentStatus, [], {
                      #documentId: documentId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i6.DriverDocumentResponse>>);

  @override
  _i4.Future<_i2.Response<_i7.DriverGetEarnings200Response>> driverGetEarnings({
    _i8.Date? from,
    _i8.Date? to,
    int? page = 1,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetEarnings, [], {
              #from: from,
              #to: to,
              #page: page,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<_i7.DriverGetEarnings200Response>
                >.value(
                  _FakeResponse_0<_i7.DriverGetEarnings200Response>(
                    this,
                    Invocation.method(#driverGetEarnings, [], {
                      #from: from,
                      #to: to,
                      #page: page,
                      #limit: limit,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i7.DriverGetEarnings200Response>>);

  @override
  _i4.Future<_i2.Response<_i9.RideResponse>> driverGetIncomingRide({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverGetIncomingRide, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i9.RideResponse>>.value(
              _FakeResponse_0<_i9.RideResponse>(
                this,
                Invocation.method(#driverGetIncomingRide, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<_i9.RideResponse>>);

  @override
  _i4.Future<_i2.Response<_i10.DriverDocumentsListResponse>>
  driverListDocuments({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverListDocuments, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<_i10.DriverDocumentsListResponse>
                >.value(
                  _FakeResponse_0<_i10.DriverDocumentsListResponse>(
                    this,
                    Invocation.method(#driverListDocuments, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i10.DriverDocumentsListResponse>>);

  @override
  _i4.Future<_i2.Response<_i11.DriverStatusResponse>> driverSetStatus({
    required _i12.DriverStatusRequest? driverStatusRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverSetStatus, [], {
              #driverStatusRequest: driverStatusRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i11.DriverStatusResponse>>.value(
                  _FakeResponse_0<_i11.DriverStatusResponse>(
                    this,
                    Invocation.method(#driverSetStatus, [], {
                      #driverStatusRequest: driverStatusRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i11.DriverStatusResponse>>);

  @override
  _i4.Future<_i2.Response<void>> driverUpdateLocation({
    required _i13.LocationUpdateRequest? locationUpdateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverUpdateLocation, [], {
              #locationUpdateRequest: locationUpdateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#driverUpdateLocation, [], {
                  #locationUpdateRequest: locationUpdateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i6.DriverDocumentResponse>> driverUploadDocument({
    required String? documentType,
    required String? documentNumber,
    required _i2.MultipartFile? image,
    _i8.Date? expiryDate,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#driverUploadDocument, [], {
              #documentType: documentType,
              #documentNumber: documentNumber,
              #image: image,
              #expiryDate: expiryDate,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i6.DriverDocumentResponse>>.value(
                  _FakeResponse_0<_i6.DriverDocumentResponse>(
                    this,
                    Invocation.method(#driverUploadDocument, [], {
                      #documentType: documentType,
                      #documentNumber: documentNumber,
                      #image: image,
                      #expiryDate: expiryDate,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i6.DriverDocumentResponse>>);

  @override
  _i4.Future<_i2.Response<_i14.GetNearbyDrivers200Response>> getNearbyDrivers({
    required double? lat,
    required double? lng,
    required String? rideType,
    double? radiusM = 5000.0,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyDrivers, [], {
              #lat: lat,
              #lng: lng,
              #rideType: rideType,
              #radiusM: radiusM,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<_i14.GetNearbyDrivers200Response>
                >.value(
                  _FakeResponse_0<_i14.GetNearbyDrivers200Response>(
                    this,
                    Invocation.method(#getNearbyDrivers, [], {
                      #lat: lat,
                      #lng: lng,
                      #rideType: rideType,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i14.GetNearbyDrivers200Response>>);

  @override
  _i4.Future<
    _i2.Response<_i15.BuiltMap<String, _i15.BuiltList<_i16.NearbyDriver>>>
  >
  getNearbyDriversAllTypes({
    required double? lat,
    required double? lng,
    double? radiusM = 5000.0,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyDriversAllTypes, [], {
              #lat: lat,
              #lng: lng,
              #radiusM: radiusM,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<
                    _i15.BuiltMap<String, _i15.BuiltList<_i16.NearbyDriver>>
                  >
                >.value(
                  _FakeResponse_0<
                    _i15.BuiltMap<String, _i15.BuiltList<_i16.NearbyDriver>>
                  >(
                    this,
                    Invocation.method(#getNearbyDriversAllTypes, [], {
                      #lat: lat,
                      #lng: lng,
                      #radiusM: radiusM,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i2.Response<
              _i15.BuiltMap<String, _i15.BuiltList<_i16.NearbyDriver>>
            >
          >);
}
