// Mocks generated by Mockito 5.4.6 from annotations
// in driver/test/features/auth/repositories/driver_auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:built_collection/built_collection.dart' as _i21;
import 'package:built_value/serializer.dart' as _i3;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sakai_api_client/src/api.dart' as _i10;
import 'package:sakai_api_client/src/api/admin_api.dart' as _i4;
import 'package:sakai_api_client/src/api/auth_api.dart' as _i5;
import 'package:sakai_api_client/src/api/driver_api.dart' as _i6;
import 'package:sakai_api_client/src/api/rides_api.dart' as _i7;
import 'package:sakai_api_client/src/api/system_api.dart' as _i8;
import 'package:sakai_api_client/src/api/users_api.dart' as _i9;
import 'package:sakai_api_client/src/model/add_payment_method_request.dart'
    as _i19;
import 'package:sakai_api_client/src/model/auth_response.dart' as _i12;
import 'package:sakai_api_client/src/model/login_request.dart' as _i13;
import 'package:sakai_api_client/src/model/logout_request.dart' as _i14;
import 'package:sakai_api_client/src/model/payment_method_details.dart' as _i18;
import 'package:sakai_api_client/src/model/payment_method_list_response.dart'
    as _i20;
import 'package:sakai_api_client/src/model/promotion.dart' as _i22;
import 'package:sakai_api_client/src/model/promotion_validate_request.dart'
    as _i23;
import 'package:sakai_api_client/src/model/refresh_request.dart' as _i15;
import 'package:sakai_api_client/src/model/register_request.dart' as _i16;
import 'package:sakai_api_client/src/model/saved_place.dart' as _i24;
import 'package:sakai_api_client/src/model/saved_place_create_request.dart'
    as _i25;
import 'package:sakai_api_client/src/model/user_profile.dart' as _i26;
import 'package:sakai_api_client/src/model/user_rating_response.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSerializers_1 extends _i1.SmartFake implements _i3.Serializers {
  _FakeSerializers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminApi_2 extends _i1.SmartFake implements _i4.AdminApi {
  _FakeAdminApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthApi_3 extends _i1.SmartFake implements _i5.AuthApi {
  _FakeAuthApi_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriverApi_4 extends _i1.SmartFake implements _i6.DriverApi {
  _FakeDriverApi_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRidesApi_5 extends _i1.SmartFake implements _i7.RidesApi {
  _FakeRidesApi_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSystemApi_6 extends _i1.SmartFake implements _i8.SystemApi {
  _FakeSystemApi_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersApi_7 extends _i1.SmartFake implements _i9.UsersApi {
  _FakeUsersApi_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_8<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SakaiApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSakaiApiClient extends _i1.Mock implements _i10.SakaiApiClient {
  MockSakaiApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
          )
          as _i2.Dio);

  @override
  _i3.Serializers get serializers =>
      (super.noSuchMethod(
            Invocation.getter(#serializers),
            returnValue: _FakeSerializers_1(
              this,
              Invocation.getter(#serializers),
            ),
          )
          as _i3.Serializers);

  @override
  void setOAuthToken(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setOAuthToken, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBearerAuth(String? name, String? token) => super.noSuchMethod(
    Invocation.method(#setBearerAuth, [name, token]),
    returnValueForMissingStub: null,
  );

  @override
  void setBasicAuth(String? name, String? username, String? password) =>
      super.noSuchMethod(
        Invocation.method(#setBasicAuth, [name, username, password]),
        returnValueForMissingStub: null,
      );

  @override
  void setApiKey(String? name, String? apiKey) => super.noSuchMethod(
    Invocation.method(#setApiKey, [name, apiKey]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.AdminApi getAdminApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAdminApi, []),
            returnValue: _FakeAdminApi_2(
              this,
              Invocation.method(#getAdminApi, []),
            ),
          )
          as _i4.AdminApi);

  @override
  _i5.AuthApi getAuthApi() =>
      (super.noSuchMethod(
            Invocation.method(#getAuthApi, []),
            returnValue: _FakeAuthApi_3(
              this,
              Invocation.method(#getAuthApi, []),
            ),
          )
          as _i5.AuthApi);

  @override
  _i6.DriverApi getDriverApi() =>
      (super.noSuchMethod(
            Invocation.method(#getDriverApi, []),
            returnValue: _FakeDriverApi_4(
              this,
              Invocation.method(#getDriverApi, []),
            ),
          )
          as _i6.DriverApi);

  @override
  _i7.RidesApi getRidesApi() =>
      (super.noSuchMethod(
            Invocation.method(#getRidesApi, []),
            returnValue: _FakeRidesApi_5(
              this,
              Invocation.method(#getRidesApi, []),
            ),
          )
          as _i7.RidesApi);

  @override
  _i8.SystemApi getSystemApi() =>
      (super.noSuchMethod(
            Invocation.method(#getSystemApi, []),
            returnValue: _FakeSystemApi_6(
              this,
              Invocation.method(#getSystemApi, []),
            ),
          )
          as _i8.SystemApi);

  @override
  _i9.UsersApi getUsersApi() =>
      (super.noSuchMethod(
            Invocation.method(#getUsersApi, []),
            returnValue: _FakeUsersApi_7(
              this,
              Invocation.method(#getUsersApi, []),
            ),
          )
          as _i9.UsersApi);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i5.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Response<_i12.AuthResponse>> authLogin({
    required _i13.LoginRequest? loginRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authLogin, [], {
              #loginRequest: loginRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i12.AuthResponse>>.value(
              _FakeResponse_8<_i12.AuthResponse>(
                this,
                Invocation.method(#authLogin, [], {
                  #loginRequest: loginRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i12.AuthResponse>>);

  @override
  _i11.Future<_i2.Response<void>> authLogout({
    required _i14.LogoutRequest? logoutRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authLogout, [], {
              #logoutRequest: logoutRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#authLogout, [], {
                  #logoutRequest: logoutRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<void>>);

  @override
  _i11.Future<_i2.Response<_i12.AuthResponse>> authRefresh({
    required _i15.RefreshRequest? refreshRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authRefresh, [], {
              #refreshRequest: refreshRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i12.AuthResponse>>.value(
              _FakeResponse_8<_i12.AuthResponse>(
                this,
                Invocation.method(#authRefresh, [], {
                  #refreshRequest: refreshRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i12.AuthResponse>>);

  @override
  _i11.Future<_i2.Response<_i12.AuthResponse>> authRegister({
    required _i16.RegisterRequest? registerRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authRegister, [], {
              #registerRequest: registerRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i12.AuthResponse>>.value(
              _FakeResponse_8<_i12.AuthResponse>(
                this,
                Invocation.method(#authRegister, [], {
                  #registerRequest: registerRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i12.AuthResponse>>);
}

/// A class which mocks [UsersApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUsersApi extends _i1.Mock implements _i9.UsersApi {
  MockUsersApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i2.Response<_i17.UserRatingResponse>> getUserRating({
    required String? userId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRating, [], {
              #userId: userId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i17.UserRatingResponse>>.value(
                  _FakeResponse_8<_i17.UserRatingResponse>(
                    this,
                    Invocation.method(#getUserRating, [], {
                      #userId: userId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i17.UserRatingResponse>>);

  @override
  _i11.Future<_i2.Response<_i18.PaymentMethodDetails>> paymentMethodsAdd({
    required _i19.AddPaymentMethodRequest? addPaymentMethodRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsAdd, [], {
              #addPaymentMethodRequest: addPaymentMethodRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i18.PaymentMethodDetails>>.value(
                  _FakeResponse_8<_i18.PaymentMethodDetails>(
                    this,
                    Invocation.method(#paymentMethodsAdd, [], {
                      #addPaymentMethodRequest: addPaymentMethodRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i18.PaymentMethodDetails>>);

  @override
  _i11.Future<_i2.Response<_i20.PaymentMethodListResponse>> paymentMethodsList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i20.PaymentMethodListResponse>>.value(
                  _FakeResponse_8<_i20.PaymentMethodListResponse>(
                    this,
                    Invocation.method(#paymentMethodsList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i20.PaymentMethodListResponse>>);

  @override
  _i11.Future<_i2.Response<void>> paymentMethodsRemove({
    required String? paymentMethodId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsRemove, [], {
              #paymentMethodId: paymentMethodId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#paymentMethodsRemove, [], {
                  #paymentMethodId: paymentMethodId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<void>>);

  @override
  _i11.Future<_i2.Response<_i18.PaymentMethodDetails>>
  paymentMethodsSetDefault({
    required String? paymentMethodId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#paymentMethodsSetDefault, [], {
              #paymentMethodId: paymentMethodId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i18.PaymentMethodDetails>>.value(
                  _FakeResponse_8<_i18.PaymentMethodDetails>(
                    this,
                    Invocation.method(#paymentMethodsSetDefault, [], {
                      #paymentMethodId: paymentMethodId,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i18.PaymentMethodDetails>>);

  @override
  _i11.Future<_i2.Response<_i21.BuiltList<_i22.Promotion>>> promotionsList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#promotionsList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<_i2.Response<_i21.BuiltList<_i22.Promotion>>>.value(
                  _FakeResponse_8<_i21.BuiltList<_i22.Promotion>>(
                    this,
                    Invocation.method(#promotionsList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i21.BuiltList<_i22.Promotion>>>);

  @override
  _i11.Future<_i2.Response<_i22.Promotion>> promotionsValidate({
    required _i23.PromotionValidateRequest? promotionValidateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#promotionsValidate, [], {
              #promotionValidateRequest: promotionValidateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i22.Promotion>>.value(
              _FakeResponse_8<_i22.Promotion>(
                this,
                Invocation.method(#promotionsValidate, [], {
                  #promotionValidateRequest: promotionValidateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i22.Promotion>>);

  @override
  _i11.Future<_i2.Response<_i24.SavedPlace>> savedPlacesCreate({
    required _i25.SavedPlaceCreateRequest? savedPlaceCreateRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesCreate, [], {
              #savedPlaceCreateRequest: savedPlaceCreateRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i24.SavedPlace>>.value(
              _FakeResponse_8<_i24.SavedPlace>(
                this,
                Invocation.method(#savedPlacesCreate, [], {
                  #savedPlaceCreateRequest: savedPlaceCreateRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i24.SavedPlace>>);

  @override
  _i11.Future<_i2.Response<void>> savedPlacesDelete({
    required String? placeId,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesDelete, [], {
              #placeId: placeId,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#savedPlacesDelete, [], {
                  #placeId: placeId,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<void>>);

  @override
  _i11.Future<_i2.Response<_i21.BuiltList<_i24.SavedPlace>>> savedPlacesList({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#savedPlacesList, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i11.Future<
                  _i2.Response<_i21.BuiltList<_i24.SavedPlace>>
                >.value(
                  _FakeResponse_8<_i21.BuiltList<_i24.SavedPlace>>(
                    this,
                    Invocation.method(#savedPlacesList, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i11.Future<_i2.Response<_i21.BuiltList<_i24.SavedPlace>>>);

  @override
  _i11.Future<_i2.Response<void>> usersDeleteMe({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#usersDeleteMe, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<void>>.value(
              _FakeResponse_8<void>(
                this,
                Invocation.method(#usersDeleteMe, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<void>>);

  @override
  _i11.Future<_i2.Response<_i26.UserProfile>> usersGetMe({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#usersGetMe, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i11.Future<_i2.Response<_i26.UserProfile>>.value(
              _FakeResponse_8<_i26.UserProfile>(
                this,
                Invocation.method(#usersGetMe, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i11.Future<_i2.Response<_i26.UserProfile>>);
}
